mixpanel/mixpanel-iphone

- Mixpanel/MPABTestDesignerConnection.h
- Mixpanel/MPABTestDesignerConnection.m
- Mixpanel/Mixpanel.h
- Mixpanel/Mixpanel.m
* automatically connects to the simulator when in debug mode
* also adds a flag to prevent connections
> Simulator autoconnect

- Mixpanel/MPSurveyQuestionViewController.m
Fix UIDeviceOrientationIsPortrait calls that should be UIInterfaceOrientationIsPortrait since you're using the the status bar orientation.
> Fix UIDeviceOrientationIsPortrait calls that should be UIInterfaceOrientationIsPortrait

- Mixpanel/MPSurveyNavigationController.m
- Mixpanel/MPSurveyQuestionViewController.m
This fixed build warnings by adding @dynamic when needed, and also fixing some type issues.
> fixed build warnings

- Mixpanel/Mixpanel.m
Fixes #207 by using the correct bundle when loading storyboards.
> Using correct bundle to load storyboards (fixes #207)

- Mixpanel/MPObjectSelector.m
This should resolve #231 and #263.
> Ensure MPObjectSelector does not accidently invoke loadView from a background thread

- Mixpanel/Mixpanel.h
Add Create Alias to docs at https://mixpanel.com/site_media/doctyl/uploads/iPhone-spec/index.html by adding the relevant info to the Mixpanel.h file in the iPhone SDK.
> Add Create Alias to docs

- Mixpanel/MPApplicationStateSerializer.m
Fix for https://github.com/mixpanel/mixpanel-iphone/issues/270
> Prevent crashes when devices are connected to A/B tests

- Mixpanel/Mixpanel.m
Fix for https://github.com/mixpanel/mixpanel-iphone/issues/294
> Fixed problem of lack for support for surveys multiple user

- Mixpanel/MPWebSocket.m
This combines the theory of #262 with some other stability and readability changes. This should resolve crashes that are the result of a race condition when attempting to clean up the connection.
> Websocket stability patches

- Mixpanel/MPNotification.m
- Mixpanel/MPSwizzler.m
Changed the last 2 NSLog calls to MixpanelError calls
> removed 2 NSLog() calls

- Mixpanel/MPDesignerEventBindingRequestMesssage.m
- Mixpanel/MPEventBinding.h
- Mixpanel/MPEventBinding.m
- Mixpanel/MPUIControlBinding.m
- Mixpanel/MPUITableViewBinding.m
- Mixpanel/Mixpanel.m
fixing spelling mistake and marking old method as deprecated
> renaming bindng to binding

- Mixpanel.xcodeproj/project.pbxproj
> Set indentation for Mixpanel project

- Mixpanel/Mixpanel.h
- Mixpanel/Mixpanel.m
Added the ability to use the $unset operation to remove People properties from profiles
> Added an unset: method to the Mixpanel People object

- Docs/HeaderDoc/Classes/Mixpanel/index.html
- Docs/HeaderDoc/Classes/Mixpanel/toc.html
- Docs/HeaderDoc/Classes/MixpanelPeople/index.html
- Docs/HeaderDoc/Protocols/MixpanelDelegate/index.html
- Docs/HeaderDoc/index.html
- Mixpanel.podspec
- Mixpanel/Mixpanel.h
- Mixpanel/Mixpanel.m
> Resolve conflicts in the ignore time param.

- Mixpanel/Mixpanel.h
- Mixpanel/Mixpanel.m
> Add functionality to unset a user's push device token.

- Mixpanel/Mixpanel.h
- Mixpanel/Mixpanel.m
> Implement readonly property isSurveyAvailable

- Mixpanel/MPSwizzler.m
Reverts mixpanel/mixpanel-iphone#439
> Revert "Change MPSwizzler to use fast enumeration in swizzle functions and in printSwizzles"

- Mixpanel-AppExtension-Info.plist
- Mixpanel.xcodeproj/project.pbxproj
- Mixpanel.xcodeproj/xcshareddata/xcschemes/Mixpanel-appExtension.xcscheme
- Mixpanel/app_extension_module.modulemap
> New target 'Mixpanel_appExtension' for carthage to use app extensions. Added 'Require Only App-Extension-Safe API' to target.

- Mixpanel/Mixpanel.m
> Fix for crash with deviceModel

- HelloMixpanel/HelloMixpanel/AppDelegate.m
- HelloMixpanel/HelloMixpanel/HelloMixpanel.storyboard
- Mixpanel/MPNotification.storyboard
- Mixpanel/MPNotificationViewController.m
Solved Issue #455 in regards to: In-app notifications truncating instead of moving text to second line. Added auto layout to the Notification Storyboard to work well with Portrait and Landscape mode.
> Solved Issue #455: In-app notifications truncating instead of moving text to second line

- Mixpanel.xcodeproj/project.pbxproj
- Mixpanel.xcodeproj/xcshareddata/xcschemes/Mixpanel-appExtension.xcscheme
- Mixpanel.xcodeproj/xcshareddata/xcschemes/Mixpanel-watchOS.xcscheme
- Mixpanel.xcodeproj/xcshareddata/xcschemes/Mixpanel.xcscheme
- Mixpanel/Mixpanel+HostWatchOS.h
- Mixpanel/Mixpanel+HostWatchOS.m
- Mixpanel/Mixpanel.h
- Mixpanel/Mixpanel.m
- Mixpanel/MixpanelWatchOS.m
- Mixpanel/module.modulemap
- Mixpanel/watchos.modulemap
* Fixed modulemap files
* Add MPTweak to Carthage project
* Require only App-Extension-Safe API for watchOS
> Resolve build issues with Carthage, Tweaks, and watchOS

- Mixpanel/MPSwizzler.m
catching swizzling exceptions that shouldn't crash the user and logging the errors
> catching swizzling exceptions

- Mixpanel/UIView+MPHelpers.m
Fix issue with ab testing regarding UITabBarButton image change showing for all buttons rather than a single one
> Fix issue with ab testing regarding UITabBarButton image change

- Mixpanel/MPNotificationViewController.m
disappearing animation of in-app had some flashing to it.
> fix for disappearing animation for mini in-apps

- Mixpanel/Mixpanel.m
A cleaner fix for #333 than #446.
> avoiding unnecessary try-catch

- Mixpanel/MPApplicationStateSerializer.m
- Mixpanel/MPFoundation.h
- Mixpanel/MPNSAttributedStringToNSDictionaryValueTransformer.m
- Mixpanel/MPNotificationViewController.m
- Mixpanel/MPSurveyNavigationController.m
- Mixpanel/MPSurveyQuestionViewController.m
- Mixpanel/MPUIImageToNSDictionaryValueTransformer.m
- Mixpanel/Mixpanel.m
- Mixpanel/UIColor+MPColor.m
- Mixpanel/UIView+MPHelpers.m
Xcode 5 support was dropped by Itunes Connect
> iOS 6 support was dropped by Mixpanel

- HelloMixpanel/HelloMixpanelTests/ABTestingTests.m
- HelloMixpanel/HelloMixpanelTests/EventBindingTests.m
- HelloMixpanel/HelloMixpanelTests/HelloMixpanelTests.m
- HelloMixpanel/HelloMixpanelTests/MPNetworkTests.m
- Mixpanel.xcodeproj/project.pbxproj
- Mixpanel/MPNetwork.m
- Mixpanel/MPNetworkPrivate.h
- Mixpanel/MPVariant.m
- Mixpanel/Mixpanel.m
- Mixpanel/MixpanelPrivate.h
> Fix all unit tests.

- .github/ISSUE_TEMPLATE.md
https://twitter.com/alloy/status/449144567259234304 ;)
> Fixing CocoaPods spelling in GH issue template

- README.md
Currently our instructions for integrating from source leave the user with the latest master branch. Adding git command to check out the latest proper release.
> Add git command to get latest version

- Mixpanel/Mixpanel.h
Addresses https://github.com/mixpanel/mixpanel-iphone/issues/586
> Updated the docs for distinctId to match the implementation.

- HelloMixpanel/HelloMixpanel/AppDelegate.m
- Mixpanel/Mixpanel.m
assert property types for nested types, upto 1000 elements long and 3 levels of nesting deep
> Assert property types nested

- Mixpanel/MPLogger.h
- Mixpanel/Mixpanel.m
should fix https://github.com/mixpanel/mixpanel-iphone/issues/608
> turn logging off by default as per documentation

- HelloMixpanel/HelloMixpanelTests/MPNetworkTests.m
- Mixpanel/MPNetwork.m
fixes https://github.com/mixpanel/mixpanel-iphone/issues/677
> stop calling UIApplication methods from background thread

- Mixpanel/MPLogger.h
- Mixpanel/Mixpanel.m
fixes https://github.com/mixpanel/mixpanel-iphone/issues/664
> make sure logging can only occur on one thread at a time

- Mixpanel/MixpanelExceptionHandler.m
should fix https://github.com/mixpanel/mixpanel-iphone/issues/692
> namespace signal and exception handlers so they won't collide as easily with other libraries

- .gitignore
- Mixpanel.xcodeproj/xcshareddata/xcschemes/[iOS] Mixpanel.xcscheme
for carthage build https://developer.apple.com/library/content/qa/qa1964/_index.html
also potentially manual or cocoapods integrations
> disabling code coverage on ios scheme to fix llvm instrumentation

- README.md
Just a little docfix from 52634ae
> Remove Mixpanel-AppExtension from README

- Mixpanel/MPVariant.m
make variants check tweaks when checking if they're equal. make tweak checking use value, not just name
> fix changing tweaks

- Mixpanel/Mixpanel.h
- Mixpanel/Mixpanel.m
Expend sharedInstanceWithToken to accept trackCrashes and automaticPushTracking
> Expend sharedInstanceWithToken

- HelloMixpanel/HelloMixpanel.xcodeproj/project.pbxproj
- HelloMixpanel/HelloMixpanelTests/MixpanelBaseTests.h
- HelloMixpanel/HelloMixpanelTests/MixpanelBaseTests.m
- HelloMixpanel/HelloMixpanelTests/MixpanelOptOutTests.m
- Mixpanel/MPNetwork.m
- Mixpanel/MPResources.m
- Mixpanel/Mixpanel.h
- Mixpanel/Mixpanel.m
- Mixpanel/MixpanelPeople.m
- Mixpanel/MixpanelPrivate.h
Background of this change:
In April, 2016, the European Union’s governing bodies passed the General Data Protection Regulation (GDPR), a set of standards and requirements for protecting the privacy and personal information of EU residents. These requirements serve to establish a uniform standard across all EU member states, but do raise the bar above current general practice. They go into effect, in May, 2018.
> Gdpr support

- .travis.yml
Update and removed some irrelevant scripts
> Clean up Travis build script

- Mixpanel/MixpanelPeople.m
Use a strong reference to self.mixPanel as done elsewhere in this method.
> Harmonized usage of strong reference

- .travis.yml
- HelloMixpanel/HelloMixpanel.xcodeproj/project.pbxproj
- HelloMixpanel/HelloMixpanel.xcodeproj/xcshareddata/xcschemes/[iOS] HelloMixpanel.xcscheme
- HelloMixpanel/HelloMixpanel/AppDelegate.m
- HelloMixpanel/HelloMixpanel/HelloMixpanel.storyboard
- HelloMixpanel/HelloMixpanelTests/Info.plist
- HelloMixpanel/HelloMixpanelTests/MixpanelBaseTests.h
- HelloMixpanel/Podfile
- Mixpanel/MPLogger.h
- Mixpanel/MPSequenceGenerator.m
- Mixpanel/MPSwizzler.h
- Mixpanel/MPSwizzler.m
- Mixpanel/MPTweakInline.m
- Mixpanel/MPUIControlBinding.m
- Mixpanel/Mixpanel.m
- Mixpanel/MixpanelExceptionHandler.m
Fixes for all the warnings for iOS 10, macOS 10.12 and above
Fixes for broken unit test for Xcode 10
Use new unified logging system
> Fix warnings for iOS 10, Xcode 10 support

- Mixpanel/Mixpanel.m
Fix the crash issue for archiving mutable array or dictionary
> Fix the crash issue for archive

- Mixpanel/Mixpanel.m
Fix when force quit, in some rare cases, the events would be sent multiple times.
> Fixes for a potential events duplication case

- HelloMixpanel/HelloMixpanelTests/SelectorEvaluatorTests.m
- Mixpanel/MPDisplayTrigger.m
- Mixpanel/SelectorEvaluator.m
Fix a bug involving equality comparison of a boolean property to a boolean value
> [ETN inapps] Fix bug in boolean comparisons

- Mixpanel/Mixpanel.m
It's a dead code not being referenced any more.
> remove the dead code for getting the watch Model

- Mixpanel/MixpanelGroupPrivate.h
https://github.com/mixpanel/mixpanel-iphone/issues/852
> fix import using angles instead of quotes

- .travis.yml
- Mixpanel/MPNotificationViewController.m
- Fix full screen in-app not showing in iOS 13
- Fix in-app mini notification icon not displaying in iOS 13
> Fix in-app notification for ios13

- HelloMixpanel/HelloMixpanel.xcodeproj/project.pbxproj
- HelloMixpanel/HelloMixpanel/HelloMixpanel.storyboard
- HelloMixpanel/NotificationServiceExtension/NotificationServiceExtension.entitlements
- Mixpanel/MPWebSocket.m
credit to https://github.com/mixpanel/mixpanel-iphone/pull/875, thanks so much @tmm1
> Add support for catalyst(iosmac) 

- HelloMixpanel/HelloMixpanel/HelloMixpanel.storyboard
- HelloMixpanel/HelloMixpanel/HomeViewController.m
- HelloMixpanel/HelloMixpanel/ViewController.m
- Mixpanel/Mixpanel.m
This will likely fix crash from `currentRadioAccessTechnology` and support Dual SIM
> Fix deprecated `currentRadioAccessTechnology` in CTTelephonyNetworkInfo

- HelloMixpanel/HelloMixpanel.xcodeproj/xcshareddata/xcschemes/[iOS] HelloMixpanel.xcscheme
- HelloMixpanel/HelloMixpanel/AppDelegate.m
- HelloMixpanel/HelloMixpanel/ViewController.m
- Mixpanel/Mixpanel.m
- Mixpanel/MixpanelPeople.m
This is to address the issue: https://github.com/mixpanel/mixpanel-iphone/issues/915
[NSMutable copy] is not thread-safe, need better write access protection.
> Fix crash when archive caused by race condition

- HelloMixpanel/HelloMixpanelTests/AutomaticEventsTests.m
- HelloMixpanel/HelloMixpanelTests/MPNetworkTests.m
- HelloMixpanel/HelloMixpanelTests/TestConstants.h
- Sources/AutomaticEvents.m
- Sources/MPNetwork.h
- Sources/MPNetwork.m
- Sources/Mixpanel.m
set content-type to `application/json` as required by Mixpanel ingestion API
> Set content-type to application/json as required by Mixpanel ingestion API

- Sources/Mixpanel.h
> fix missing import MixpanelGroup

- Mixpanel.podspec
> Fix duplicated header in the CocoaPods build

- .github/workflows/mixpanel.yml
Pod linting fails for watchOS in Xcode 14: https://github.com/CocoaPods/CocoaPods/issues/11558
> Disable watchOS in CI

- HelloMixpanel/PrivacyInfo.xcprivacy
- Mixpanel.xcodeproj/project.pbxproj
Add privacy manifest declaring use of User Defaults
Addresses: https://github.com/mixpanel/mixpanel-iphone/issues/1018
> Add privacy manifest
