Mixpanel/MPABTestDesignerSnapshotRequestMessage.m

When the app is restarted in the simulator, and reconnects to the switchboard, there can be a queued snapshot request message that gets delivered to the device. This snapshot request doesn't contain the required snapshot configuration, and the app has lost its cached version as it's been restarted.

Ignore stale snapshot messages

---

Mixpanel/MPSurveyNavigationController.m
Mixpanel/MPSurveyQuestionViewController.m

"Auto property synthesis will not synthesize property 'view'; it will be implemented by its superclass, use @dynamic to acknowledge intention"

Fix warnings from XCode 6.3 iOS 8.3 for overriding properties

---

Mixpanel/Mixpanel.h

`<code>identify:<code>` to `<code>identify:</code>`

Fixing incorrect closing tag in comments

---

Mixpanel/Mixpanel.m

In continuation of https://github.com/mixpanel/mixpanel-iphone/issues/232#issuecomment-135206887

Reset `shownNotifications` on Mixpanel#reset call

---

Mixpanel/MPNotificationViewController.m
Mixpanel/UIView+MPHelpers.m

xcode throws a warning but we have "Treat warnings as errors" options on. So, it wont actually compile

Fix for xcode 7

---

Mixpanel/MPNotificationViewController.h
Mixpanel/MPNotificationViewController.m
Mixpanel/Mixpanel.h
Mixpanel/Mixpanel.m

* Added a new property called miniNotiicationBackgroundColor to primary interface
* Setting this property will set the background color of the notification view
* If this property is not set, we fall back to previous behavior

Add property to customize in-app mini notifications background

---

HelloMixpanel/HelloMixpanelTests/HelloMixpanelTests.m
Mixpanel/Mixpanel.m

This pull request fixes an issue explained in #268
Additionally it fixes an issue when Notifications and Surveys were prevented from being presented if a notifications has been failed to be presented before.

Don't present Notifications on top of UIAlertController

---

HelloMixpanel/HelloMixpanel.xcodeproj/project.pbxproj

I have 2 space indentation set up in global Xcode preferences.
So when I was editing a file in this project Xcode was indenting everything with 2 spaces. So I had to fix indentation manually to match your coding style.
Fortunately Xcode has an option to set up indentation in project file :)

Set indentation in Xcode project

---

Mixpanel/MPWebSocket.m

Currently MPWebSocket.m continuously spams the console with debug logging enabled. These messages should use the MessagingDebug macro instead of MixpanelDebug.

Changed all usage of MixpanelDebug macro to MessagingDebug in MPWebSocket.m

---

Mixpanel/Mixpanel.h

1. Pass NSNumber* instead of int where required for this method:
- (void)increment:(NSString *)property by:(NSNumber *)amount;
2. Replace this sample code line (which doesn't compile):
[mixpanel.people identify:@"CURRENT USER DISTINCT ID"];
...with this line:
[mixpanel identify:@"CURRENT USER DISTINCT ID"];
3. Remove this sample code line that doesn't compile:
[mixpanel.people identify:distinctId];

Documentation fixes in Mixpanel.h to fix iOS sample code

---

Mixpanel/Mixpanel.m

If the flush interval is dynamically changing, we could end up in a situation where no events are sent during the user session.

Flush events after setting flush interval

---

Mixpanel/Mixpanel.m

If the app is background/foregrounded very quickly, we can't guarantee that we end all the tasks after they expire since self.taskId keeps a reference to the last executed task on the background.

Make sure all background tasks are killed when expired

---

Mixpanel/Mixpanel.m

Variable 'backgroundTask' could be uninitialized when captured by block.

Fixes analyzer issue

---

Mixpanel/Mixpanel.m

We get around 20 crashes a day with the following call stack. We debugged the issue and found an incorrectly initialised property. This fix prevents those crashes.
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSSet initWithSet:copyItems:]: set argument is not an NSSet'
*** First throw call stack:
(
0   CoreFoundation                      0x04a4ca84 __exceptionPreprocess + 180
1   libobjc.A.dylib                     0x04443e02 objc_exception_throw + 50
2   CoreFoundation                      0x0497cf4f -[NSSet initWithSet:copyItems:] + 1231
3   CoreFoundation                      0x0498e504 +[NSSet setWithSet:] + 68
4   Mixpanel                            0x00cbe9ab __58-[Mixpanel checkForDecideResponseWithCompletion:useCache:]_block_invoke …
```

Fixed crash when calling `checkForDecideResponseWithCompletion:useCache:` 

---

Mixpanel/Mixpanel.m

Our production app has been seeing crashes in the wild in these two Mixpanel functions. Both crash logs indicate invalid subscript access on the dictionary which led us to believe the mutableCopy failed to return a valid object for some reason.

Protect against nil dictionary access

---

Mixpanel/MPTweak.h
Mixpanel/Mixpanel.h
Mixpanel/Mixpanel.m

This will make interoperability much better for Swift developers, and require less use of Optional types.

Nullability audit on MPTweak, Mixpanel, and MixpanelPeople.

---

Mixpanel/Mixpanel.m

These are backwards and causing issues when segmenting by these properties to view cross-platform statistics.
You may want to review this from your end as far as impact to current projects -- this will change the props going forward to be correct, but will not fix those which are currently using the wrong behavior.

Flip app release and version to be correct

---

Mixpanel/MPWebSocket.h
Mixpanel/MPWebSocket.m

Rename websocket categories so we won't collide with SRWebSocket.

---

Mixpanel/Mixpanel.h
Mixpanel/Mixpanel.m

This feature lets client integrations decide on whether IP addresses should be sent along with other event tracking data. Normally, we want as much data as we can get, including the wonderful geo-location benefits possible with sending an IP address with events.
However, in some scenarios, our client app's privacy policies don't permit having the level of location specificity that is possible with an IP address.
As such, it is useful to be able to control whether we continue to transmit IP addresses (the default) or suppress doing so.
```
// Initialize the library with our mixpanel token:
[Mixpanel sharedInstanceWithToken:mixpanelToken];
// Retrieve singleton instance of underlying analytics provider:
self.analyticsProvider = [Mixpanel sharedInstance]; …
```

Option to suppress IP Address collection

---

Mixpanel/Mixpanel.m

Fixes a race condition between timeEvent: and track: that leads to negative $duration values, due to the start time being captured asynchronously, while the event timestamp is recorded on the main thread. To prevent the start time from being evaluated after the event has been tracked, we simply capture the start time inside of timeEvent: before dispatching asynchronously.

Prevent negative $duration values

---

Mixpanel/Mixpanel.m

These should be reset as well, otherwise, they're unarchived from a previous instance/project.

On reset, initialize variants and eventBindings

---

Mixpanel/Mixpanel.h
Mixpanel/Mixpanel.m

It is unable to get lib version before the instance is initialized
Now I'm using mixpanel like this:
``` swift
class Tracker {
static let sharedInstance = Tracker()
let mixpanel: Mixpanel 
private init() {
mixpanel = Mixpanel.sharedInstanceWithToken(AppKeys.mixpanelAppKey)
mixpanel.registerSuperProperties(getEventSessionParameters())
// other statement
}
static func getEventSessionParameters() -> [String : AnyObject] {    
var results = [String : AnyObject]()
results['Mixpanel Version'] = sharedInstance.mixpanel.libVersion
// Other statement
return results
}
}
```
It will become something like an `endless loop`, so i need some way like that to get lib version.

Add class method to get libversion

---

Mixpanel.xcodeproj/project.pbxproj

This will prevent a linker error due to this class not being included in this project.

Add the new exception handler to the Carthage project.

---

Mixpanel/Mixpanel.m

Currently there is no flush after an alias is created within the iOS library. Without a flush, this leaves the potential for a race condition where an event could be stored with the wrong ID as the alias does not resolve in time. By forcing a flush, we can be sure the alias resolves before the next calls come in with the aliased distinct ID.
We currently do this in Android [here](https://github.com/mixpanel/mixpanel-android/blob/ca5c0d9e74217c6d5ce5e9afa58397c5d1346a14/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L360) and should add to iOS for parity.

Add flush after createAlias call

---

Mixpanel/Mixpanel.m

$unset expects a list of properties not a string

fixed bug in removePushDeviceToken

---

Mixpanel.xcodeproj/project.pbxproj

Carthage build was failing because of that:
```
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “E8FVX7QLET” were found.
```

Remove team id from xcodeproj

---

Mixpanel/MPDesignerEventBindingRequestMesssage.m

Protect against a possible crash when an MPEventBinding constructor returns nil, likely due to renamed views or malformed JSON.

---

Mixpanel/Mixpanel.m

Currently the SDK will check for new experiments via ```joinExperimentsWithCallback``` and process the updates received from Mixpanel servers. When a new variant is received or no variants are received, the running variant is [marked](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L1376-L1377) under the set ```toFinishVariants``` as it should be.
The issue is that for these finished variants, we call to [finish](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPVariant.m#L231-L233) which does not actually end the variant shown to the user. Instead, we should be calling [stop](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPVariant.m#L221-L229) to stop running this variant and allow the new changes from Mixpanel to be …

Apply new variants / Turn off experiments when calling joinExperimentsWithCallback

---

Mixpanel/MPVariant.m

Prevent `NSNull` from crashing `MPValueTransformer`. Resolves #434

Guard transformValue in MPVariant

---

Mixpanel/Mixpanel.m

We are using takeover (full screen) notifications. When user interacts with them Mixpanel sdk launches an url which is handled by our app. 
In our case those urls are handled by presenting some view controller on top of current top presented controller.
The problem we hit pretty often is that the our view controller is not presented. And in console I see something like:
> Warning: Attempt to present <UINavigationController: 0x134a5b600> on <MPTakeoverNotificationViewController: 0x136a37650> whose view is not in the window hierarchy!
I suppose this happens because in current implementation `[[UIApplication sharedApplication] openURL:url]` is called first and after that `MPTakeoverNotificationViewController` get dismissed. So at the time our url handled gets called …

Open url after MPTakeoverNotificationViewController is dismissed

---

Mixpanel/Mixpanel.m

Resolves watchOS integration when using more than one instance of the Mixpanel SDK. Resolves #449.

Fix for watchOS integration

---

Mixpanel/Mixpanel.m

Call archive on every flush, regardless of whether a completion block is passed.
Resolves #441

Archive on every flush

---

Mixpanel/UIImage+MPAverageColor.m

Fix mp_important color to be more safe, and leverage CoreGraphics instead of hard coded magic numbers.
Resolves #450

Crash fix for mp_important color

---

.gitignore

When this framework is added via carthage with the `--use-submodules` flag, it builds it in the mixpanel-iphone/Carthage/Build directory, marking this submodule as `dirty`. Adding `Carthage/Build` to the gitignore list fixes this :)

Added Carthage/Build to the gitignore list

---

Mixpanel/Mixpanel.m

Currently, if we get an error back from decide in `checkForDecideResponseWithCompletion:completion useCache:` we log it and return without calling the completion handler. This prevents `joinExperimentsWithCallback:` from ever calling its callback block. This fix simply calls the completion handler (if it exists) with `nil` values in the event of a decide error.

Make sure completion handler is called even when a decide check returns an error

---

Mixpanel/Mixpanel+HostWatchOS.m

Currently the Apple Watch is looking for a ```messageType``` of ```track:``` when sending Mixpanel messages to the iPhone. Since the code for ```MixpanelWatchOS``` always sends the selector as ```track:properties:```, events are not being properly relayed back to the iPhone.
This PR is to look for the selector ```track:properties:``` from the Apple Watch and allow Mixpanel messages to be sent along to the iPhone.

Fix track calls from Apple Watch

---

Mixpanel/Mixpanel.h
Mixpanel/Mixpanel.m

Add enableABTestDesigner property to the public API to allow disabling the AB test designer without recompiling and providing the `DISABLE_MIXPANEL_AB_DESIGNER` macro.

Programatically disable A/B test designer

---

Mixpanel/MPWebSocket.m

Background: When `mixpanel-iphone` is integrated using a `git submodule` to a project that has `Threat warnings as error` enabled, this triggers a compile error. 
Solution: Disabled the warning using the `clang diagnostic ignored "-Wunused-result"`

Ignored the unused result warning

---

HelloMixpanel/HelloMixpanel.xcodeproj/project.pbxproj
HelloMixpanel/HelloMixpanel.xcodeproj/xcshareddata/xcschemes/HelloMixpanel.xcscheme
HelloMixpanel/HelloMixpanelTests/MPPersistenceTests.m
Mixpanel.xcodeproj/project.pbxproj
Mixpanel/MPPersistence.h
Mixpanel/MPPersistence.m
Mixpanel/Mixpanel.m

This migrates all file handling and persistence functionality in to an `MPPersistence` helper. This alos adds a new test suite focused exclusively on persistence.
Tests Status:
Code Coverage Report:

Refactor persistence

---

Mixpanel/MPEventBinding.m
Mixpanel/MPObjectSelector.m
Mixpanel/MPUIControlBinding.m
Mixpanel/MPUITableViewBinding.m
Mixpanel/Mixpanel.m

NSHashSet didn't have a proper comparable, which caused all codeless bindings to keep accumulating with duplicates. Also this caused all codeless events to be unswizzled then re-swizzled all at once. 
Also, codeless events were tracked multiple times each time we got a decide response inside the same session

Swizzling and codeless fix

---

HelloMixpanel/HelloMixpanelTests/MPNotificationTests.m

This test exercises a real code path that caused a crash in v2.9.8 for a customer due to an invalid image URL. This test confirms that the move to `NSURLComponents` did actually resolve that issue.

Add MPNotification test with malformed image URL from customer issue.

---

HelloMixpanel/HelloMixpanel.xcodeproj/project.pbxproj
HelloMixpanel/HelloMixpanelTests/MPNetworkTests.h
HelloMixpanel/HelloMixpanelTests/MPNetworkTests.m
Mixpanel/MPNetwork.h
Mixpanel/MPNetwork.m
Mixpanel/MPNetworkPrivate.h
Mixpanel/MPNotification.m
Mixpanel/Mixpanel.m

Remove nonsensical URL encoding from MPNotification.
Remove MPNetworkTests.h and move to MPNetworkPrivate.h, fix tests since there was a small refactor, add test that checks full URL is built correctly for decide changes.

First pass at better URL encoding

---

Mixpanel/MixpanelPeople.m

Original removePushDeviceToken function would make device token value a list, which would result in the $remove operation not working:
$remove":{"$ios_devices":["1719128325f7036b765fcd5087bbac542b6ae0becdd1003674faaad6f1918721"]}
Through making it a string we can ensure that the $remove operation will work:
$remove":{"$ios_devices":"1719128325f7036b765fcd5087bbac542b6ae0becdd1003674faaad6f1918721"}

removePushDeviceToken fix

---

Mixpanel.xcodeproj/project.pbxproj
Mixpanel/Mixpanel.h
Mixpanel/app_extension_module.modulemap

- Added `app_extension_module.modulemap` file
`Mixpanel/module.modulemap` contains reference to `MPTweak` which is not included in the AppExtension target. Hence the new `Mixpanel/app_extension_module.modulemap` specific for the AppExtension.
- Changed import statement for `MixpanelPeople.h` in `Mixpanel.h` file
File is not found when compiling for AppExtension target with `#import <Mixpanel/MixpanelPeople.h>` as AppExtension has a different `$PRODUCT_NAME`
- Specified different `PRODUCT_BUNDLE_IDENTIFIER` for AppExtension target
Installation to the device will fail if the binary has multiple frameworks with the same bundle identifier. In the case of Parent App with Extension that needs to link to two different targets, `Mixpanel` and `MixpanelAppExtension`, we need to have 2 copies of …

Enabled AppExtension target for a non WatchOS extension

---

Mixpanel.xcodeproj/project.pbxproj

I have a code sign problem on the v3.0.3, I can't use Mixpanel v3.0.3 as a carthage dependency because of that. Here is the fix.

Fix Code Sign iOS

---

Mixpanel/MPNetwork.m

In the new version having a custom server url path like
https://domain.com/v1/track/mixpanel wouldn't work because the url components' path is overwritten with a hardcoded path rather than the hardcoded path is appended only.

Fixes an issue that prevents having custom server urls

---

Mixpanel/MPClassDescription.h
Mixpanel/MPClassDescription.m

While compiling with Swift, modules enabled, and the `-fcxx-modules` flag, build failed in line 15:
`- (BOOL)isDescriptionForKindOfClass:(Class)class;`
Changing the parameter name from `class` to `aClass`, as seen in [`NSObject`s declarations](https://developer.apple.com/reference/objectivec/1418956-nsobject/1418511-iskindofclass) fixed it.

Renames MPClassDescription method parameter name

---

Mixpanel/Mixpanel.h
Mixpanel/Mixpanel.m
Mixpanel/MixpanelPrivate.h

Ported the safety check from our js lib, which only changes the distinct_id when calling identify if the given distinct_id is different from the existing distinct_id and the alias. Required creating an alias property.
For reference: https://github.com/mixpanel/mixpanel-js/blob/master/src/mixpanel-core.js#L1339-L1343

Adding identify: safety check

---

HelloMixpanel/HelloMixpanelTests/ABTestingTests.m
HelloMixpanel/HelloMixpanelTests/HelloMixpanelTests.m
HelloMixpanel/HelloMixpanelTests/MPNetworkTests.m
HelloMixpanel/HelloMixpanelTests/MixpanelBaseTests.h
HelloMixpanel/HelloMixpanelTests/MixpanelBaseTests.m
HelloMixpanel/HelloMixpanelTests/MixpanelPeopleTests.m
Mixpanel/MPNetwork.h
Mixpanel/MPNetwork.m
Mixpanel/MPNetworkPrivate.h
Mixpanel/Mixpanel.m
Mixpanel/MixpanelPeople.m
Mixpanel/MixpanelPrivate.h

here's my notes:
goal: non-network and network happen in parallel
non-network puts stuff in eventsQueue and peopleQueue
flush takes stuff out of eventsQueue and peopleQueue
need to lock on adding, removing, reading
need to lock on saving to disk (reading actually only happens on init so should be okay though maybe should do it anyway)
as it stands flush will flush whatever was added before. naively changing makes it so it will continue flushing as long as stuff keeps getting added in. should read all stuff at start to not have endless flushing
reset needs to wait on flushes as well
flush and other network queue stuff should be dispatched from the serial queue so the pattern of track -> flush always has that track in the flush instead of only sometimes… so everything on the network queue …

Separate network queue

---

Mixpanel/MPNetwork.m

Hello, 
According to the documentation: “Passing nil to setQueryItems removes the query component of the NSURLComponents object.”
If the serverUrl is custom and it already has query parameters, they will be overridden when setting queryItems to nil, that’s the situation in my company, so I guess that it could potentially happen to someone else.
With this change we should not modify current behavior and we’ll allow developers to use query parameters in their serverUrl
Thank you so much for your time.

Don't set queryItems if they're nil

---

Mixpanel/MPNSAttributedStringToNSDictionaryValueTransformer.m
Mixpanel/MPNetwork.m
Mixpanel/MPNotification.h
Mixpanel/MPNotificationViewController.m
Mixpanel/Mixpanel.h
Mixpanel/MixpanelPeople.m

Good to hear that you are going to remove the survey deprecated code soon, The reason behind this PR is to eliminate/silence all the warnings from mixpanel code. Since the project I am involved in is treating warnings as errors (and hence those prevents compiling and running). Plus no warnings is a good thing :)
Anyways, I updated this PR to only include general warnings fixes.

General warning fixes for v3.1.2

---

Mixpanel/Mixpanel.m
Mixpanel/MixpanelPrivate.h

Here is an issue @peymano and I have found and debugged together.
---
**Given** you have two boolean tweak variables. One of them is true by default, and another one is false.
```objective-c
MPTweakValue(@"test1", YES);
MPTweakValue(@"test2", NO);
```
**Given** on Mixpanel's website we run A/B test with two variants:
* Variant 1: `test1: NO; test2: YES`.
* Variant 2: `test1: NO; test2: NO`
**Given** we have two users with Mixpanel profiles with different distinct_ids. User1 got Variant 1 and User2 got Variant 2.
1. In our mobile app sign in as user 1 and call `Mixpanel#joinExperimentsWithCallback:`. If we happen to look into what `https://decide.mixpanel.com/decide?...` returns, it will have two tweaks:
```json
{
"notifications": [],
"surveys": [],
"variants": [
{
"tweaks": [
{
"name": …
```

Reset MPTweakStore on Mixpanel#reset

---

Mixpanel/Mixpanel.h
Mixpanel/Mixpanel.m

https://github.com/mixpanel/mixpanel-iphone/issues/642
@yarneo i chose to allow them to check the current duration because it gives more flexibility for the user and also the other option would be a bit messy because we archive `timedEvents` so either the implementation wouldn't be clean or we'd have to have a way to migrate `timedEvents`

add a method to check elapsed time for a timed event

---

HelloMixpanel/HelloMixpanelTests/HelloMixpanelTests.m
Mixpanel/Mixpanel.m

```
{
‘mp’: {
‘c’: $campaign_id,
‘m’: $message_id,
}
}
```
```
{
event: $campaign_received,
properties: {
‘campaign_id': $campaign_id,
‘message_id’: $message_id
}
}
```
```
{
‘mp’: {
‘c’: $campaign_id,
‘m’: $message_id,
‘additional_params_1’: $param1,
‘additional_params_2’: $param2,
}
}
```
```
{
event: $campaign_received,
properties: {
‘campaign_id': $campaign_id,
‘message_id’: $message_id,
‘additional_params_1’: $param1,
‘additional_params_2’: $param2,
}
}
```

Support tracking journey_id for push open events

---

Mixpanel/Mixpanel.m

If someone joins an experiment that is sent to all users prior to identify being called, the experiment id will never be added to their $experiments People property. I'm not sure what the purpose of checking for self.people.distinctId was, but I don't think it's necessary.

Don't require identify to merge $experiments People

---

Mixpanel.xcodeproj/project.pbxproj

SKIP_INSTALL option was set to YES explicitly for every target except target `Mixpanel`, which caused issues with archiving client app. This sets SKIP_INSTALL = YES on project level, propagating to all targets.

Specify SKIP_INSTALL = YES on project level

---

Mixpanel/Mixpanel.m

fix it so backgrounding task correctly waits for flush to complete. synchronized decideResponseCached because it's used from both serial and network queues. synchronized archive calls so they don't always have to happen from serial queue anymore

fix for backgrounding task not waiting for flush to complete

---

Mixpanel/Mixpanel.h
Mixpanel/Mixpanel.m
Mixpanel/MixpanelExceptionHandler.m

* changed to using `sigaction` instead of `signal` as it appears more standard, and handlers registered with `signal` will be returned with `sigaction` so we'll still call them, whereas the opposite may not be true
* no longer unregister signal and exception handling after getting one signal or exception
* calling on main thread seemed unnecessary so i got rid of that
* moved `archive` call after tracking automatic event, not before (it seemed to work regardless)
this should fix the issues with mixpanel blocking other crash reporting in https://github.com/mixpanel/mixpanel-iphone/issues/704

fix signal and exception handling

---

Mixpanel/Mixpanel.m

crash was caused by swizzling with the wrong block when UNUserNotification has a delegate but it doesn't implement the method we're looking for
fixes https://github.com/mixpanel/mixpanel-iphone/issues/722

fix a crash in push notif handling

---

Mixpanel/MPUIControlBinding.m

Fix for this issue: https://github.com/mixpanel/mixpanel-iphone/issues/732

Removing targets should be always performed on the main thread

---

Mixpanel/MixpanelExceptionHandler.m

should fix https://github.com/mixpanel/mixpanel-iphone/issues/750 and https://github.com/mixpanel/mixpanel-iphone/issues/744

remove global variables in MixpanelExceptionHandler

---

Mixpanel/MPTweakInline.m

The entry is full of nil objects when running in AddressSanitizer. Don't try to derefence a nil pointer.

Fix Dereference Crash Running in AddressSanitizer

---

Mixpanel/Mixpanel.m

i'm pretty sure there's no real issue here, since it shouldn't be doing ab tests for app extensions anyway
addresses https://github.com/mixpanel/mixpanel-iphone/issues/759

fix typo with macro.

---

Mixpanel/MixpanelPeople.m

cc: @amitayfeder1
Right now `addPushDeviceToken` blindly attempts to call `pushDeviceTokenToString` which returns `nil` if deviceToken isn't present. Passing `nil` to NSDictionary causes a crash. This change checks if there's actually a push token before attempting to convert to a string. 
We used to handle this scenario in 2.9.9 via the logic here: https://github.com/mixpanel/mixpanel-iphone/blob/v2.9.9/Mixpanel/Mixpanel.m#L2093-L2095

only attempt to convert and add push token if present

---

Mixpanel/MPTakeoverNotificationViewController~iphoneportrait.xib

Full screen In-apps are not displayed correctly on iPhone X if they have the secondary button (see attached screenshots).

Two-Button, Full screen In-apps don't fit on iPhone X

---

Mixpanel/Mixpanel.m

This addresses the issue I raised in #779 where arguments that are declared are not respected in the method (likely due to a copy-paste error).  These changes should allow the method to match what the header documentation states.

Ensure the trackCrashes & automaticPushTracking arguments are respected (#779)

---

Mixpanel/MPTakeoverNotificationViewController~ipad.xib
Mixpanel/MPTakeoverNotificationViewController~iphonelandscape.xib
Mixpanel/MPTakeoverNotificationViewController~iphoneportrait.xib

This PR is to address the issue 
https://github.com/mixpanel/mixpanel-iphone/issues/774
"Button to dismiss fullscreen in-app message is too tiny, hard to tap"

Enlarge the dismiss button for in-app notification

---

Mixpanel/MPNotificationViewController.m

It looks like the code always resize the image by 2x smaller and scale it up if necessary. Since we have appended "@2x" to image url, resizing is no longer needed.

Fix Images in mobile in-apps being resized and are blurry on display

---

Mixpanel.xcodeproj/project.pbxproj

The series 4 Apple Watch announced today uses a new architecture.
Also, the deployment target for watchOS must be increased to 3.0, otherwise uploads to the App Store will result in the following: 
> ERROR ITMS-90081: "This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later."

Add new watch architecture

---

Mixpanel/MPNotificationViewController.m

When a takeover notification received while using the keyboard, keyboard stays on the window like the image below and doesn't disappear until to close the notification.

hide keyboard while showing inapp-message

---

HelloMixpanel/HelloMixpanel.xcodeproj/project.pbxproj
HelloMixpanel/HelloMixpanel/HelloMixpanel-Bridging-Header.h
HelloMixpanel/HelloMixpanelTests/MPNotificationTests.m
HelloMixpanel/HelloMixpanelTests/SelectorEvaluatorTests.swift
Mixpanel.podspec
Mixpanel.xcodeproj/project.pbxproj
Mixpanel/MPDisplayTrigger.h
Mixpanel/MPDisplayTrigger.m
Mixpanel/MPNotification.h
Mixpanel/MPNotification.m
Mixpanel/Mixpanel.m
Mixpanel/MixpanelPrivate.h
Mixpanel/SelectorEvaluator.swift

**Event Triggered InApps**
Currently users have no control over when an InApp notification shows up. With this release users can now control when an InApp gets displayed based on an event that they track within their app. This "trigger" event is defined during message creation. You can additionally filter the event based on properties that are tracked along with the event for even finer controls.

Add support for display triggers in InApp notifications

---

Mixpanel/MixpanelExceptionHandler.m

This is not needed cause `track` will do the archive and call it in sync will cause potential crashes

remove the sync archive after the exception handler being triggered

---

HelloMixpanel/HelloMixpanelTests/MixpanelOptOutTests.m
Mixpanel/Mixpanel.m
Mixpanel/MixpanelPrivate.h

Change the default behavior for setting `optOutTrackingByDefault` in  the Mixpanel initialization method.
- We will not override opt out persistence with `optOutTrackingByDefault` the flag since opt-out default state is supposed to be used as an initial state while GDPR information is being collected

Opt-out default state won't override user opt out local persistence

---

.travis.yml
Mixpanel/MixpanelExceptionHandler.m
release.py

Change `NSHashtable`  to `NSMutableArray` to avoid crash in iOS 13 with [NSConcreteHashTable countByEnumeratingWithState].  The `NSHashtable` can store the weak reference of Mixpanel instance, but in this case it's not necessary. 
issue:
https://github.com/mixpanel/mixpanel-iphone/issues/867

Xcode11 support and fix crash with MixpanelExceptionHandler in iOS 13

---

HelloMixpanel/HelloMixpanelTests/HelloMixpanelTests.m
HelloMixpanel/HelloMixpanelTests/MPNotificationTests.m
HelloMixpanel/HelloMixpanelTests/MixpanelBaseTests.m
Mixpanel/MPNetwork.m
Mixpanel/Mixpanel.m
Mixpanel/MixpanelPrivate.h

- Optimize archive logic:
avoid using `@synchronized` and using GCD instead
- fix CTTelephonyNetworkInfo crash
let CTTelephonyNetworkInfo instance always stay alive by changing it to static to avoid being released by iOS.

Optimize archive logic and fix CTTelephonyNetworkInfo crash

---

.travis.yml
HelloMixpanel/HelloMixpanel/AppDelegate.m
HelloMixpanel/HelloMixpanel/HelloMixpanel.storyboard
HelloMixpanel/HelloMixpanel/ViewController.m
HelloMixpanel/HelloMixpanelTests/HelloMixpanelTests.m
HelloMixpanel/HelloMixpanelTests/MPNetworkTests.m
HelloMixpanel/HelloMixpanelTests/MPNotificationTests.m
Mixpanel/MPNetwork.m

This is to address https://github.com/mixpanel/mixpanel-iphone/issues/909 (Crashes in encodeArrayForAPI: and convertFoundationTypesToJSON: under iOS 13)
In iOS 13 there is a bug for `encodeArrayAsJSONData:` if the input `array` in `encodeArrayAsJSONData:(NSArray *)array` contains corrupted characters(not valid UTF-8), it will lead to a crash. see radar https://openradar.appspot.com/radar?id=4964054569320448  (NSJSONSerialization crashes on iOS 13) The fix is to check whether the string is a valid UTF-8 before sending to Mixpanel. Mixpanel backend can only handle UTF-8 string.

Fix NSJSONSerialization crash in iOS 13

---

Mixpanel/Mixpanel.m

Temporarily remove the ability to monitor the radio change due to a crash issue that might relate to the API from Apple
https://openradar.appspot.com/46873673

temporarily remove  monitoring the radio change due to a bug from Apple

---

Mixpanel/MPLogger.h

The os_log* functions will not capture context-specific information unless inlined.

os_log* wrappers need to be always inlined

---

Mixpanel/MPConnectIntegrations.m

address #938 
Fix crash when integrating with urbanairship 14.0+ due to `UAirship push channelID` has been removed and changed to `UAirship channel identifier`. The fix was to `UAirship.push().channelID -> UAirship.channel().identifier)`
For more details:
https://github.com/urbanairship/ios-library/blob/main/Documentation/Migration/migration-guide-13-14.md

migrate to Airship 14.0 for the Urban Airship integration 

---

HelloMixpanel/HelloMixpanelTests/HelloMixpanelTests.m
HelloMixpanel/HelloMixpanelTests/MixpanelOptOutTests.m
Mixpanel/Mixpanel.m

We are deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)). Starting from the next version, we will not automatically track pushes sent from Mixpanel and crashes by default. However, you can still opt-in them by calling 
```
+ (Mixpanel *)sharedInstanceWithToken:(NSString *)apiToken launchOptions:(nullable NSDictionary *)launchOptions trackCrashes:(BOOL)trackCrashes automaticPushTracking:(BOOL)automaticPushTracking;
```
and set `trackCrashes` and `automaticPushTracking` to YES.

Set `automaticPushTracking` and `trackCrashes` to NO by default when init the SDK

---

Mixpanel/Mixpanel.m

**Overview**
This PR updates logic for retrieving **$carrier** property to try to find the carrier that has a name that is not empty. 
More details on the reasoning behind the following change are described in this issue https://github.com/mixpanel/mixpanel-iphone/issues/949
**Changes**
In order to reduce the number of events where **$carrier** is `undefined` now it iterates over a collection of carriers and tries to find some that name is not empty. Once the proper carrier is found it breaks the loop. In case all carriers don't have a name it uses the first object as a fallback to be in line with previous logic.

Carrier name retrieval

---

Mixpanel/Mixpanel.m

In parity with the swift library, removing the check on existing alias when identify is called since the integration with Braze can prevent identify from working correctly. Also not relevant with ID merge.

Remove alias check when calling identify

---

Sources/MixpanelPersistence.m

Fix the warning
`
*** -[NSKeyedUnarchiver validateAllowedClass:forKey:]: NSSecureCoding allowed classes list contains [NSObject class], which bypasses security by allowing any Objective-C class to be implicitly decoded. Consider reducing the scope of allowed classes during decoding by listing only the classes you expect to decode, or a more specific base class than NSObject. This will become an error in the future. 
`

Add NSSecureCoding allowed classes to avoid warning

---

Sources/MixpanelPersistence.m

`shownNotifications` were archived as an `NSSet` in the properties file, even though they won't be used, we still need to be able to unarchive them when we migrate from the legacy archive file to 4.0. This PR adds the `NSSet` class to the list of classes that can be unarchived.
Fixes: https://github.com/mixpanel/mixpanel-iphone/issues/971

add [NSSet class] to unarchiveFromFile

---

HelloMixpanel/HelloMixpanelTests/HelloMixpanelTests.m
Sources/Mixpanel.h
Sources/Mixpanel.m

Since SPM doesn't provide a way to specify pre-processor macros we need to make `MIXPANEL_UNIQUE_DISTINCT_ID` configurable via an API. This PR adds that functionality.
Addresses: https://github.com/mixpanel/mixpanel-iphone/issues/970

add useUniqueDistinctId

---

Sources/MixpanelPersistence.m

previously we were putting $distinct_id on all records, $distinct_id is disallowed on groups records, so this was causing them to be rejected by the api

only add $distinct_id to people records

---

Mixpanel.podspec
Mixpanel.xcodeproj/project.pbxproj

Due to: https://stackoverflow.com/questions/77139617/clang-error-sdk-does-not-contain-libarclite-at-the-path

Bump minimum iOS deployment target to 13.0

---

Sources/MPDB.m

This should fix the issues reported in https://github.com/mixpanel/mixpanel-iphone/issues/1027
Without the error handling, serialization is returning nil and then trying to insert that in some array, which causes a crash.

Adds error handling for serialization failure in MPDB readRows
